### PR TITLE
Migrate cw20-wrapped to cosmwasm 1.0

### PR DESCRIPTION
**Pull request by measure-fi**
https://github.com/palomachain/paloma/issues/177

## Background

After attempting to migrate from cw20-legacy to cw20 as well, here
instead we are forking cw20-legacy into the repo and bringing its
versions up to match. This will assist in testing future potential
cw20 migrations.

## Testing completed

- [x] Existing tests pass

### CODE REVIEW

**Comment by measure-fi** [comment]
@Vizualni What are your thoughts about cw20-legacy? The name makes it sound relatively untrustworthy but other than that it is just a contract.

**Comment by Vizualni** [comment]
> @Vizualni What are your thoughts about cw20-legacy? The name makes it sound relatively untrustworthy but other than that it is just a contract.

What was the original name? I generally don't see a problem with the name. If you do, I am happy to discuss possible alternatives :)

**Review by Vizualni — APPROVED** [review]

**Comment by measure-fi** [comment]
> What was the original name? I generally don't see a problem with the name. If you do, I am happy to discuss possible alternatives :)

It' a fork of https://github.com/terra-money/cosmwasm-contracts/tree/feature/wasm-1.0/contracts/cw20-legacy (same name).

**Comment by measure-fi** [comment]
That is the original name. My question is essentially how important is it
to migrate to normal cw20 right now?

**Pull request merged**
